version: '2'
volumes:
  ibmmq:
    driver: local
services:
  ibmmq:
    image: 'docker.io/ibmcom/mq'
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    ports:
      - '1414:1414'
      - '9443:9443'
    volumes:
      - ibmmq:/data/ibmmq
    container_name: ibmmq

#    mssql:
#      image: 'docker.io/ibmcom/mq'
#      environment:
#        - LICENSE=accept
#        - MQ_QMGR_NAME=QM1
#      ports:
#        - '1414:1414'
#        - '9443:9443'
#      container_name: ibmmq


#services:
#  grpc-service:
#    build:
#      context: grpc
#      dockerfile: Dockerfile
#    container_name: grpc-service
#    image: sacom-grpc:latest
#    ports:
#      - "9000:9000"

#  orchestrator-service:
#    build:
#      context: orchestrator-service
#      dockerfile: Dockerfile
#    container_name: orchestrator-service
#    image: sacom-orchestrator:latest
#    ports:
#      - "9000:9000"

#  receiver-service:
#    build:
#      context: receiver-service
#      dockerfile: Dockerfile
#    container_name: receiver-service
#    image: sacom-receiver-service:latest
#    ports:
#      - "9002:9002"

#  sender-service:
#    build:
#      context: sender-service
#      dockerfile: Dockerfile
#    container_name: sender-service
#    image: sacom-sender:latest
#    ports:
#      - "9001:9001"