#server:
#  port: 9290
#  servlet.context-path: /camel
#  undertow.max-http-post-size: 0
camel:
  springboot.name: RestCamel
#  rest:
#    host: /camel/*
#    port: 9290
#  servlet.mapping.context-path: /camel-rest/*
timer.period: 2000

spring:
  application.name: camel
  main.allow-bean-definition-overriding: true
  profiles:
    active: dev
  jackson.default-property-inclusion: non_absent
#ibm:
#  mq:
#    queueManager: QM1
#    channel: DEV.ADMIN.SVRCONN
#    connName: localhost(1414)
#    user: admin
#    password: passw0rd
queues.queueDev: DEV.QUEUE.1

#logging:
#  level:
#    root: INFO
#    web: DEBUG
#    sql: DEBUG

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE