spring:
  application.name: ibmmq
  main.allow-bean-definition-overriding: true
  jackson.default-property-inclusion: non_absent
  profiles:
    active: dev
    include: temporal
#  config.activate.on-profile: dev
