server:
  port: 9292
  servlet.context-path: /orches
  undertow.max-http-post-size: 0

spring:
  application.name: orches
  main.allow-bean-definition-overriding: true
  jackson.default-property-inclusion: non_absent
  config:
    activate.on-profile: dev
    import: temporal