// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenderService.proto

package grpc;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
