// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenderService.proto

package grpc;

public final class SenderServiceOuterClass {
  private SenderServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_TransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_TransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SenderService.proto\022\004grpc\"h\n\022Transacti" +
      "onRequest\022\025\n\rtransactionId\030\001 \001(\t\022\021\n\tacco" +
      "untId\030\002 \001(\t\022\023\n\013recipientId\030\003 \001(\t\022\023\n\013debi" +
      "tAmount\030\004 \001(\003\"%\n\023TransactionResponse\022\016\n\006" +
      "result\030\001 \001(\t2\215\001\n\rSenderService\022=\n\006deduct" +
      "\022\030.grpc.TransactionRequest\032\031.grpc.Transa" +
      "ctionResponse\022=\n\006refund\022\030.grpc.Transacti" +
      "onRequest\032\031.grpc.TransactionResponseB\002P\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_TransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_TransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_TransactionRequest_descriptor,
        new java.lang.String[] { "TransactionId", "AccountId", "RecipientId", "DebitAmount", });
    internal_static_grpc_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_TransactionResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
